language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nirfuchs73/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nirfuchs73/docker-react npm run test
